### ISSUE TITLE
RFC: addon api

### ISSUE THREAD

**Issue by lifeart** [lifeart/ember-language-server#12]
### WHY?

Idea is - allow users to install langerver extensions into project.

langerver extension -> npm package with special field in package.json and handler in js file.

in package.json we specify features we wanna handle, and handler expose api methods for it.

---------------

## ELS addon example

`package.json`

```ts
"ember-language-server": {
    "entry": "./lib/langserver",
    "version": 1,
    "debug"? : true, // allow hot-reload addon logic without server restart
    "capabilities": {
      "definitionProvider": true,
      "referencesProvider": true,
      "completionProvider": true,
      "codeActionProvider": true
    }
}
```

`lib/langserver.js`
```js
module.exports.onReference = async function(projectRoot, params) {
  return [
    {
      range: {
        end: {
          character: 0,
          line: 0
        },
        start: {
          character: 0,
          line: 0
        }
      },
      uri: "file://path/to/resolved/component.js"
    }
  ];
};

module.exports.onComplete = async function(projectRoot, { focusPath }) {
  if (focusPath.node.type === "ElementNode") {
    return [
      {
        label: "MyCustomComponent"
      },
      {
        label: "MyHardcodedComponent"
      }
    ];
  }
};

module.exports.onDefinition = async function(projectRoot, params) {
  return [
    {
      range: {
        end: {
          character: 0,
          line: 0
        },
        start: {
          character: 0,
          line: 0
        }
      },
      uri: "file://path/to/resolved/component.js"
    }
  ];
};

```

refs: https://github.com/vastec/ember-unused-components/issues/56

--------

## Addon API interface

```ts
import { Definition, FileChangeType, Diagnostic, TextDocument, Location, TextDocumentIdentifier, Position, CompletionItem, CodeActionParams } from 'vscode-languageserver';
import Server from '../server';
import ASTPath from './../glimmer-utils';

type Executor = (server: Server, command: string, args: any[]) => any;
type Linter = (document: TextDocument) => Diagnostic[];
type Watcher = (uri: string, change: FileChangeType) => any;

type MatchResultType =
  | 'helper'
  | 'service'
  | 'route'
  | 'controller'
  | 'modifier'
  | 'template'
  | 'component'
  | 'model'
  | 'transform'
  | 'adapter'
  | 'serializer';

interface MatchResult {
  type: MatchResultType;
  name: string;
}

interface Project {
  root: string; // project entry path
  addCommandExecutor(key: string, fn: Executor): void;
  addLinter(fn: Linter): void;
  addWatcher(fn: Watcher): void;
  matchPathToType(filePath: string): null | MatchResult;
}

interface Registry {
  component: {
    [componentName: string]: string[] // files, related to component
  },
  service: {
    [serviceName: string]: string[] // files, related to service
  },
  routePath: {
    [routePath: string]: string[] // files, related to route (templates, controllers, routes)
  }
}

interface Command {
   command: string // els.executeInEmberCLI
   arguments: any[] // first argument - file path / project root, if command scoped to project
}
interface Server {
  getRegistry(projectRoot: string): Registry;
  onExecute(command: Command): any;
  getUsages(normalizedName: string): string[]; // return list of files, related to token
}

interface BaseAPIParams {
  server: Server;
  textDocument: TextDocumentIdentifier;
  position: Position;
}
interface ExtendedAPIParams {
  focusPath: ASTPath;
  type: 'script' | 'template';
}
interface ReferenceFunctionParams extends BaseAPIParams {
  results: Location[];
}
interface CompletionFunctionParams extends ExtendedAPIParams {
  results: CompletionItem[];
}
interface DefinitionFunctionParams extends ExtendedAPIParams {
  results: Location[];
}

interface CodeActionFunctionParams extends CodeActionParams {
  results: (Command | CodeAction)[];
  server: Server;
  document: TextDocument
}

type ReferenceResolveFunction = (root: string, params: ReferenceFunctionParams) => Promise<Location[]>;
type CompletionResolveFunction = (root: string, params: CompletionFunctionParams) => Promise<CompletionItem[]>;
type DefinitionResolveFunction = (root: string, params: DefinitionFunctionParams) => Promise<Location[]>;
type CodeActionResolveFunction = (root: string, params: CodeActionParams) => Promise<(Command | CodeAction)[] | undefined | null>;
type InitCallback = (server: Server, project: Project) => void;


export interface AddonAPI {
  onReference: undefined | ReferenceResolveFunction;
  onComplete: undefined | CompletionResolveFunction;
  onDefinition: undefined | DefinitionResolveFunction;
  onCodeAction: undefined | CodeActionResolveFunction;
  onInit: undefined | InitCallback;
}
```

----------

Addon api:

[addon-api.ts](https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/src/utils/addon-api.ts)

Addons: 
* [els-a11y-addon](https://github.com/lifeart/els-a11y-addon)
* [els-component-extraction-addon](https://github.com/lifeart/els-component-extraction-addon)
* [els-addon-typed-templates](https://github.com/lifeart/els-addon-typed-templates)
* [els-addon-docs](https://github.com/lifeart/els-addon-docs)
* [els-intl-addon](https://github.com/lifeart/els-intl-addon)

Ember addons with langserver API:
* [ember-cli-inline-template-only-components](https://github.com/lifeart/ember-cli-inline-template-only-components)
* [ember-template-imports](https://github.com/knownasilya/ember-template-imports)
* [ember-fast-cli](https://github.com/lifeart/ember-fast-cli)

Wiki: https://github.com/lifeart/ember-language-server/wiki

**Comment by lifeart** [comment]
simple autocomplete addon file structure

`lib/langserver.js`
```js
function onComplete(root, { focusPath, textDocument, position, server, results, type }) { 

/* 

 root - project root file (absolute path), like C://users/user/documents/repos/repo/project
 focusPath - AST node, created by langserver
 textDocument - https://github.com/microsoft/vscode-languageserver-node/blob/master/textDocument/src/main.ts#L116
 position - https://github.com/microsoft/vscode-languageserver-node/blob/master/textDocument/src/main.ts#L22
 server -  language server instance
 results - data, resolved by langserver (you can patch it)
 type - "script" or "template"

*/

  // https://microsoft.github.io//language-server-protocol/specifications/specification-3-14/#textDocument_completion
  return [{label: "this.name"}];
}

module.exports.onComplete = onComplete;
```

`package.json`
```json
{
  "name": "dummy-provider",
   "ember-language-server": {
      "entry": "./lib/langserver",
      "capabilities": {
        "completionProvider": true
      }
  }
}
```

**Comment by lifeart** [comment]
should we chain API calls and results like `addon(addon(addon(results)))` or merge like
`[...addon(results), ...addon(results), ...addon(results)]`?

existing implementation allow original results modification and following merge approach, all results (including original) will be merged.

I think chain structure is more maintainable, anyway we have only one runloop, don't think we get mutch benefits from merge-like approach, but it relatively safe (one addon can't broke anover).

**Comment by Baltazore** [comment]
@lifeart do we expect that some `addon(results)` call fail ? If so I think merging results would be more error prone, but it is only concern here...

**Comment by lifeart** [comment]
@Baltazore all addon calls wrapped into try / catch and in case of "catch" we can take next addon and pas existing results as argument.

**Comment by chriskrycho** [comment]
@lifeart this proposal needs some fleshing out! I think I'm following it, but it could use (a) more text explaining the intent, and (b) explicit API definitions and contracts. (What I see looks good, to be clear, but it needs more detail on those fronts please!) Can you add some of those details and also perhaps add the expected TypeScript interfaces for these API hooks?

**Comment by lifeart** [comment]
for chained calls we can use `ember-addon` filed and read `before`, `after` packages.
after we will be able to create ordered call chain, using https://github.com/krisselden/dag-map

**Comment by lifeart** [comment]
@chriskrycho addon API ref: https://github.com/lifeart/ember-language-server/pull/14/commits/62093530955b6204f36597cee054b2fa01f7cbe7

**Comment by lifeart** [comment]
[`lifeart.vscode-ember-unstable@0.2.42`](https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-ember-unstable) available for users who want to test this functionality

**Comment by knownasilya** [comment]
Seeing this with v0.2.44

```
[Error - 7:21:25 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'visit' of undefined
  Code: -32603 
```

I was testing in a dummy app though.. did test in the `app` folder as well, but no errors there just nothing happens.

**Comment by knownasilya** [comment]
Changed

```json
"capabilities": {
      "completionProvider": {
        "resolveProvider": true
      }
    }
```
to
```json
    "capabilities": {
      "completionProvider": true
    }
```

and got in app auto complete but saw this error:

> [Error - 7:27:47 PM] Request completionItem/resolve failed.
  Message: Unhandled method completionItem/resolve
  Code: -32601 

I define this method: `module.exports.onComplete = onComplete;` and the first line is a console.log

**Comment by lifeart** [comment]
@knownasilya is `ast-types` exists inside `node_modules`? (https://github.com/lifeart/ember-language-server/blob/component-context-info-origin/src/symbols/js-document-symbol-provider.ts#L16)

regarding ` Unhandled method completionItem/resolve` - is it happens 2+ times or only once in first run?

**Comment by lifeart** [comment]
@knownasilya issues fixed in `vscode-ember-unstable@0.2.45`

**Comment by knownasilya** [comment]
Thanks for fixing those! I don't see any errors, but the api still doesn't seem to be called, https://github.com/crashco/ember-template-component-import/blob/autocomplete/lib/langserver.js

**Comment by lifeart** [comment]
@knownasilya you going well! 

try remove "type" and rename "name" -> "label" 
![image](https://user-images.githubusercontent.com/1360552/69932695-2936b300-14dd-11ea-9d04-1719d6a176d2.png)

completion Item structure:

```
// import { CompletionItem, CompletionItemKind } from 'vscode-languageserver';

{
  kind?: CompletionItemKind.Class,
  label: 'ComponentName,
  detail?: 'my custom component'
};
```

possible kind's:

![image](https://user-images.githubusercontent.com/1360552/69932838-b5e17100-14dd-11ea-90e8-14987e0eec99.png)


```ts
export interface CompletionItem {
    /**
     * The label of this completion item. By default
     * also the text that is inserted when selecting
     * this completion.
     */
    label: string;
    /**
     * The kind of this completion item. Based of the kind
     * an icon is chosen by the editor.
     */
    kind?: CompletionItemKind;
    /**
     * A human-readable string with additional information
     * about this item, like type or symbol information.
     */
    detail?: string;
    /**
     * A human-readable string that represents a doc-comment.
     */
    documentation?: string | MarkupContent;
    /**
     * Indicates if this item is deprecated.
     */
    deprecated?: boolean;
    /**
     * Select this item when showing.
     *
     * *Note* that only one completion item can be selected and that the
     * tool / client decides which item that is. The rule is that the *first*
     * item of those that match best is selected.
     */
    preselect?: boolean;
    /**
     * A string that should be used when comparing this item
     * with other items. When `falsy` the [label](#CompletionItem.label)
     * is used.
     */
    sortText?: string;
    /**
     * A string that should be used when filtering a set of
     * completion items. When `falsy` the [label](#CompletionItem.label)
     * is used.
     */
    filterText?: string;
    /**
     * A string that should be inserted into a document when selecting
     * this completion. When `falsy` the [label](#CompletionItem.label)
     * is used.
     *
     * The `insertText` is subject to interpretation by the client side.
     * Some tools might not take the string literally. For example
     * VS Code when code complete is requested in this example `con<cursor position>`
     * and a completion item with an `insertText` of `console` is provided it
     * will only insert `sole`. Therefore it is recommended to use `textEdit` instead
     * since it avoids additional client side interpretation.
     *
     * @deprecated Use textEdit instead.
     */
    insertText?: string;
    /**
     * The format of the insert text. The format applies to both the `insertText` property
     * and the `newText` property of a provided `textEdit`.
     */
    insertTextFormat?: InsertTextFormat;
    /**
     * An [edit](#TextEdit) which is applied to a document when selecting
     * this completion. When an edit is provided the value of
     * [insertText](#CompletionItem.insertText) is ignored.
     *
     * *Note:* The text edit's range must be a [single line] and it must contain the position
     * at which completion has been requested.
     */
    textEdit?: TextEdit;
    /**
     * An optional array of additional [text edits](#TextEdit) that are applied when
     * selecting this completion. Edits must not overlap (including the same insert position)
     * with the main [edit](#CompletionItem.textEdit) nor with themselves.
     *
     * Additional text edits should be used to change text unrelated to the current cursor position
     * (for example adding an import statement at the top of the file if the completion item will
     * insert an unqualified type).
     */
    additionalTextEdits?: TextEdit[];
    /**
     * An optional set of characters that when pressed while this completion is active will accept it first and
     * then type that character. *Note* that all commit characters should have `length=1` and that superfluous
     * characters will be ignored.
     */
    commitCharacters?: string[];
    /**
     * An optional [command](#Command) that is executed *after* inserting this completion. *Note* that
     * additional modifications to the current document should be described with the
     * [additionalTextEdits](#CompletionItem.additionalTextEdits)-property.
     */
    command?: Command;
    /**
     * An data entry field that is preserved on a completion item between
     * a [CompletionRequest](#CompletionRequest) and a [CompletionResolveRequest]
     * (#CompletionResolveRequest)
     */
    data?: any;
}
```

**Comment by lifeart** [comment]
@knownasilya project addon api lookup added in `lifeart.vscode-ember-unstable@0.2.46` (now you don't need to plug addon into app to test els integration, langserver will check project's `package.json` for possible API's)

**Comment by knownasilya** [comment]
Sweet, thanks @lifeart

**Comment by lifeart** [comment]
extended debug: https://github.com/lifeart/ember-language-server/pull/26

**Comment by lifeart** [comment]
published `lifeart.vscode-ember-unstable@0.2.47` with extended debug and ability to hotreload addons logic without langserver restart.

all you need is add `debug: true` in `package.json` section, related to `els`

example:

```js
"ember-language-server": {
    "entry": "./lib/langserver",
    "version": 1,
    "debug" : true, // allow hot-reload addon logic without server restart
    "capabilities": {
      "definitionProvider": true,
      "referencesProvider": true,
      "completionProvider": true
    }
}
```

**Comment by lifeart** [comment]
tips:  how to log some data?

![image](https://user-images.githubusercontent.com/1360552/69996743-b58bb900-1563-11ea-99a4-f8f287b13bd6.png)

**Comment by lifeart** [comment]
workspaces support: https://github.com/lifeart/ember-language-server/pull/27 `vscode-ember-unstable@0.2.48`

**Comment by lifeart** [comment]
more addons:

https://github.com/lifeart/els-addon-typed-templates
https://github.com/lifeart/els-addon-docs

**Comment by lifeart** [comment]
# How to debug an `els-addon`?

## There is few steps.

Register addon path globally (to skip addon installation step)

`.vscode/settings.json`

```json
{
    "els.local.addons": ["C:\\Users\\ember\\els-addon-typed-templates"],
}
```
or

link UELS addon to project in package.json (just like any dependency)

---

## Next steps

1. We need to run UELS in debug mode
1. We need to connect to UELS server (after it's initialization
1. Done! Now we can use breakpints!

---

## To run UELS in debug mode, we need to get currently installed extension path.

Let's figure out extension path, for me it:

`C:/Users/lifeart/.vscode/extensions/lifeart.vscode-ember-unstable-1.3.2`,
 
and we need to write it to 

`.vscode/launch.json`
```json
{
   "version":"0.1.0",
   "configurations":[
      {
         "name":"Launch UELS Extension",
         "type":"extensionHost",
         "request":"launch",
         "runtimeExecutable":"${execPath}",
         "args":[
            "--extensionDevelopmentPath=C:/Users/lifeart/.vscode/extensions/lifeart.vscode-ember-unstable-1.3.2"
         ],
         "stopOnEntry":false,
         "sourceMaps":true,
         "outFiles":[
            "C:/Users/lifeart/.vscode/extensions/lifeart.vscode-ember-unstable-1.3.2/out/src/**/*.js"
         ]
      },
      {
         "name":"Attach to UELS Server",
         "type":"node",
         "request":"attach",
         "port":6004,
         "sourceMaps":true,
         "protocol":"inspector",
         "outFiles":[
            "C:/Users/lifeart/.vscode/extensions/lifeart.vscode-ember-unstable-1.3.2/node_modules/@lifeart/ember-language-server/lib/**/*.js"
         ],
         "restart":true,
         "smartStep":true
      }
   ]
}
```

## Steps:

1. Run `Launch UELS Extension`
1. Select an Ember project (for debbuging)
1. Run `Attach to UELS Server`
1. Set debug point

![image](https://user-images.githubusercontent.com/1360552/81563277-ba6c5880-939e-11ea-92db-456409a56f14.png)
